In [1]:
# Importing necessary libraries

import cv2
import numpy as np


#Loading the original image

imagedata_brt = cv2.imread("newdir//frame0.jpg")
cv2.imshow("Original Image", imagedata_brt)


#matrix of one which is multiplied by a scaler value of 60, matrix has dimensions same as our input image

Intensity_Matrix = np.ones(imagedata_brt.shape, dtype = 'uint8') * 60

#print Intensity Matrix

print(Intensity_Matrix)

#Add Intensity Matrix to iput image in order to increse the brightness
brightened_image = cv2.add(imagedata_brt, Intensity_Matrix)
cv2.imshow("Bright", brightened_image)

#Subtract Intensity Matrix from input image in order ti decrease the brightness
darkened_image= cv2.subtract(imagedata_brt, Intensity_Matrix)
cv2.imshow("dark", darkened_image)



cv2.waitKey(0)
cv2.destroyAllWindows()

[[[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 ...

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]]


In [33]:
import cv2

import os,glob

from os import listdir,makedirs

from os.path import isfile,join
path = 'C://Users//Patel//Downloads//playment//newdir' # Source Folder
dstpath = 'C://Users//Patel//Downloads//playment//Brightness' # Destination Folder
try:
    makedirs(dstpath)
except:
    print ("Directory already exist, images will be written in same folder")
# Folder won't used
files = list(filter(lambda f: isfile(join(path,f)), listdir(path)))




for image in files:
    try:
        img = cv2.imread(os.path.join(path,image))
        Intensity_Matrix = np.ones(img.shape, dtype = 'uint8') * 60
        
        #Add Intensity Matrix to iput image in order to increse the brightness
        brightened_image = cv2.add(img, Intensity_Matrix)
        #cv2.imshow("Bright", brightened_image)
       # gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        dstPath = join(dstpath,image)
        cv2.imwrite(dstPath,brightened_image)
    except:
        print ("{} is not converted".format(image))
for fil in glob.glob("*.jpg"):
    try:
        image = cv2.imread(fil)
        
        brightened_image = cv2.add(image, Intensity_Matrix)
        dstPath = join(dstpath,image)
        cv2.imwrite(os.path.join(dstpath,fil),brightened_image)
    except:
        print('{} is not converted')
        


Directory already exist, images will be written in same folder


In [ ]:
import cv2

import os,glob

from os import listdir,makedirs

from os.path import isfile,join
path = 'C://Users//Patel//Downloads//playment//newdir' # Source Folder
dstpath = 'C://Users//Patel//Downloads//playment//Darkness' # Destination Folder
try:
    makedirs(dstpath)
except:
    print ("Directory already exist, images will be written in same folder")
# Folder won't used
files = list(filter(lambda f: isfile(join(path,f)), listdir(path)))



darkened_image= cv2.subtract(imagedata_brt, Intensity_Matrix)
cv2.imshow("dark", darkened_image)



for image in files:
    try:
        img = cv2.imread(os.path.join(path,image))
        Intensity_Matrix = np.ones(img.shape, dtype = 'uint8') * 60
        
        #Subtract Intensity Matrix from input image in order ti decrease the brightness
        darkened_image= cv2.subtract(imagedata_brt, Intensity_Matrix)
        dstPath = join(dstpath,image)
        cv2.imwrite(dstPath,darkened_image)
    except:
        print ("{} is not converted".format(image))
for fil in glob.glob("*.jpg"):
    try:
        image = cv2.imread(fil)
        
        darkened_image = cv2.add(image, Intensity_Matrix)
        dstPath = join(dstpath,image)
        cv2.imwrite(os.path.join(dstpath,fil),darkened_image)
    except:
        print('{} is not converted')
        
